#!/usr/bin/env python3
"""
monitor_manager.py — Manage scheduled flight price monitoring tasks.

Uses WorkBuddy automation system (TOML-based) under:
  ~/.workbuddy/automations/

Supports cron-like schedule expressions compatible with both WorkBuddy and OpenClaw.

Usage:
    python monitor_manager.py add   --from BJS --to SYX --date 2026-03-25 --freq daily --threshold 1500
    python monitor_manager.py add   --from HGH --to SIA --date 2026-03-26 --freq 6h
    python monitor_manager.py list
    python monitor_manager.py pause --id flight-BJS-SYX-2026-03-25
    python monitor_manager.py remove --id flight-BJS-SYX-2026-03-25
    python monitor_manager.py run   --id flight-BJS-SYX-2026-03-25  # manual trigger
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

try:
    import tomllib          # Python 3.11+
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        tomllib = None       # fallback: manual parsing

AUTOMATIONS_DIR = Path.home() / ".workbuddy" / "automations"
SCRIPTS_DIR = Path(__file__).parent

# ── Frequency → cron expression ─────────────────────────────────────────────
FREQ_MAP = {
    "hourly": "FREQ=HOURLY;INTERVAL=1",
    "1h": "FREQ=HOURLY;INTERVAL=1",
    "2h": "FREQ=HOURLY;INTERVAL=2",
    "3h": "FREQ=HOURLY;INTERVAL=3",
    "6h": "FREQ=HOURLY;INTERVAL=6",
    "12h": "FREQ=HOURLY;INTERVAL=12",
    "daily": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU;BYHOUR=9;BYMINUTE=0",
    "morning": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU;BYHOUR=9;BYMINUTE=0",
    "twice-daily": "FREQ=HOURLY;INTERVAL=12",
}

FREQ_LABELS = {
    "hourly": "每小时", "1h": "每1小时", "2h": "每2小时",
    "3h": "每3小时", "6h": "每6小时", "12h": "每12小时",
    "daily": "每天9:00", "morning": "每天早上9:00", "twice-daily": "每天早晚各1次",
}


def make_task_id(dep: str, arr: str, date: str) -> str:
    return f"flight-{dep.upper()}-{arr.upper()}-{date}"


def add_monitor(dep: str, arr: str, date: str, freq: str,
                threshold: float = None, return_date: str = None) -> str:
    task_id = make_task_id(dep, arr, date)
    task_dir = AUTOMATIONS_DIR / task_id
    task_dir.mkdir(parents=True, exist_ok=True)

    rrule = FREQ_MAP.get(freq, FREQ_MAP["daily"])
    threshold_note = f"，低于¥{threshold}提醒" if threshold else ""
    label_freq = FREQ_LABELS.get(freq, freq)
    route_label = f"{dep.upper()} → {arr.upper()}"

    # Build the monitoring prompt — with strict date locking
    threshold_note = f"，若最低价 ≤ ¥{threshold} 则触发低价提醒" if threshold else ""
    rt_note = f"，同时关注 {return_date} 返程价格" if return_date else ""
    notify_step = (
        f"4. 若触发低价提醒，运行推送通知：python {SCRIPTS_DIR / 'notify.py'} "
        f"--title \"机票低价提醒 {dep}→{arr}\" "
        f"--body \"{dep}→{arr} 出行日期{date} 最低价¥<最低价>，低于阈值¥{threshold}！推荐航班<航班号>\" "
        f"--url \"https://flights.ctrip.com/itinerary/oneway/{dep.lower()}-{arr.lower()}?depdate={date}\""
    ) if threshold else ""

    prompt = (
        f"【机票价格监控】出行日期：{date}（注意：搜索时必须使用此出行日期，不能用今天日期）。"
        f"请按以下步骤执行：\n"
        f"1. 运行：python {SCRIPTS_DIR / 'search_flights.py'} --from {dep} --to {arr} --date {date}"
        + (f" --max-price {threshold}" if threshold else "")
        + f"\n2. 若脚本 source 为 fallback，使用 search_query 字段执行 web_search（仅一次），"
        f"搜索词必须包含出行日期 {date}{rt_note}{threshold_note}。"
        f"\n3. 运行：python {SCRIPTS_DIR / 'price_history.py'} append "
        f"--from {dep} --to {arr} --date {date} --price <最低价> --flight \"<航班号>\""
        + (f" --threshold {threshold}" if threshold else "")
        + (f"\n{notify_step}" if notify_step else "")
    )

    toml_content = f'''# Flight Monitor Task
# Auto-generated by flight-monitor skill

[automation]
name = "机票监控 {route_label} {date}"
prompt = """{prompt}"""
rrule = "{rrule}"
status = "ACTIVE"

[meta]
dep = "{dep.upper()}"
arr = "{arr.upper()}"
date = "{date}"
freq = "{freq}"
threshold = {threshold if threshold else "null"}
return_date = "{return_date or ""}"
created_at = "{datetime.now().isoformat()}"
'''

    toml_file = task_dir / "automation.toml"
    toml_file.write_text(toml_content, encoding="utf-8")

    return (
        f"✅ 已添加监控任务\n\n"
        f"- **ID:** `{task_id}`\n"
        f"- **航线:** {route_label}\n"
        f"- **出行日期:** {date}\n"
        f"- **监控频率:** {label_freq}{threshold_note}\n"
        f"- **配置文件:** `{toml_file}`\n\n"
        f"> 提示：任务已写入 WorkBuddy 自动化目录，下次触发时将自动执行。"
    )


def list_monitors() -> str:
    AUTOMATIONS_DIR.mkdir(parents=True, exist_ok=True)
    tasks = [
        d for d in AUTOMATIONS_DIR.iterdir()
        if d.is_dir() and d.name.startswith("flight-")
    ]
    if not tasks:
        return "暂无机票监控任务。"

    lines = ["## 当前机票监控任务", "", "| ID | 航线 | 日期 | 频率 | 阈值 | 状态 |",
             "|----|------|------|------|------|------|"]
    for task_dir in sorted(tasks):
        toml_file = task_dir / "automation.toml"
        if not toml_file.exists():
            continue
        try:
            content = toml_file.read_text(encoding="utf-8")
            meta = _simple_toml_parse(content, "meta")
            auto = _simple_toml_parse(content, "automation")
            dep = meta.get("dep", "")
            arr = meta.get("arr", "")
            date = meta.get("date", "")
            freq = FREQ_LABELS.get(meta.get("freq", ""), meta.get("freq", ""))
            threshold = meta.get("threshold", "−")
            status = auto.get("status", "ACTIVE")
            lines.append(
                f"| `{task_dir.name}` | {dep}→{arr} | {date} | {freq} "
                f"| {f'¥{threshold}' if threshold and threshold != 'null' else '−'} | {status} |"
            )
        except Exception as e:
            lines.append(f"| `{task_dir.name}` | (解析失败: {e}) | | | | |")
    return "\n".join(lines)


def pause_monitor(task_id: str) -> str:
    toml_file = AUTOMATIONS_DIR / task_id / "automation.toml"
    if not toml_file.exists():
        return f"❌ 未找到任务 `{task_id}`"
    content = toml_file.read_text(encoding="utf-8")
    updated = content.replace('status = "ACTIVE"', 'status = "PAUSED"')
    toml_file.write_text(updated, encoding="utf-8")
    return f"⏸ 已暂停任务 `{task_id}`"


def remove_monitor(task_id: str) -> str:
    task_dir = AUTOMATIONS_DIR / task_id
    if not task_dir.exists():
        return f"❌ 未找到任务 `{task_id}`"
    for f in task_dir.iterdir():
        f.unlink()
    task_dir.rmdir()
    return f"🗑 已删除任务 `{task_id}`"


def run_monitor(task_id: str) -> str:
    """Manually trigger a monitor task by reading its prompt and executing."""
    toml_file = AUTOMATIONS_DIR / task_id / "automation.toml"
    if not toml_file.exists():
        return f"❌ 未找到任务 `{task_id}`"
    content = toml_file.read_text(encoding="utf-8")
    meta = _simple_toml_parse(content, "meta")
    dep = meta.get("dep", "")
    arr = meta.get("arr", "")
    date = meta.get("date", "")
    threshold = meta.get("threshold")
    threshold_arg = f"--max-price {threshold}" if threshold and threshold != "null" else ""
    print(f"🔍 手动触发：{dep} → {arr} on {date}")
    # Execute query
    os.system(
        f'python "{SCRIPTS_DIR / "query_flights.py"}" '
        f"--from {dep} --to {arr} --date {date} {threshold_arg}"
    )
    return ""


def _simple_toml_parse(content: str, section: str) -> dict:
    """Minimal TOML section parser (no dependency on tomllib)."""
    result = {}
    in_section = False
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith(f"[{section}]"):
            in_section = True
            continue
        if stripped.startswith("[") and in_section:
            break
        if in_section and "=" in stripped and not stripped.startswith("#"):
            key, _, val = stripped.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            result[key] = val
    return result


def main():
    parser = argparse.ArgumentParser(description="Flight monitor task manager")
    sub = parser.add_subparsers(dest="cmd")

    p_add = sub.add_parser("add")
    p_add.add_argument("--from", dest="dep", required=True)
    p_add.add_argument("--to", dest="arr", required=True)
    p_add.add_argument("--date", required=True)
    p_add.add_argument("--freq", default="daily",
                       help="Frequency: hourly/1h/2h/3h/6h/12h/daily/twice-daily")
    p_add.add_argument("--threshold", type=float)
    p_add.add_argument("--return-date", dest="return_date")

    p_pause = sub.add_parser("pause")
    p_pause.add_argument("--id", required=True)

    p_remove = sub.add_parser("remove")
    p_remove.add_argument("--id", required=True)

    p_run = sub.add_parser("run")
    p_run.add_argument("--id", required=True)

    sub.add_parser("list")

    args = parser.parse_args()

    if args.cmd == "add":
        print(add_monitor(args.dep, args.arr, args.date, args.freq,
                          args.threshold, args.return_date))
    elif args.cmd == "list":
        print(list_monitors())
    elif args.cmd == "pause":
        print(pause_monitor(args.id))
    elif args.cmd == "remove":
        print(remove_monitor(args.id))
    elif args.cmd == "run":
        run_monitor(args.id)
    else:
        parser.print_help()


if __name__ == "__main__":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    main()
